### ISSUE TITLE
The menus under dev.ardupilot.com need to be re-structured

### ISSUE THREAD

**Issue by gmorph** [diydrones/ardupilot-wiki-issue-tracker#26] opened 2015-01-28 06:26 UTC
These menu items have grown over time.  They now need to be sorted out as lots of them at the top level should be grouped together under the same level.  Will action this once the new Wiki format comes online.

**Comment by hamishwillee** [comment] 2015-01-28 06:33
Good idea. 
1. Not sure how, but can you make yourself a member of this project so we can assign tasks to you?
2. While you're doing that, please think about how you might group the topics by category or tag.

**Comment by hamishwillee** [comment] 2015-08-12 05:22
@gmorph Closing this as duplicate of #107 (now mostly complete)

**Closed by hamishwillee** 2015-08-12 05:22 UTC
Labels: bug, dev-wiki, docs, duplicate
